# Generated by Django 5.0.4 on 2024-04-25 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_provincia', models.CharField(default='Cidade de Maputo', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='direccao_regional',
            name='nome_direccao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='direccao_regional',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.provincia'),
        ),
    ]
