# Generated by Django 5.0.4 on 2024-06-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_assigned_to_team',
            field=models.BooleanField(default=False),
        ),
    ]
