# Generated by Django 5.0.4 on 2024-06-14 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_user_is_assigned_to_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_assigned_to_team',
        ),
    ]
