# Generated by Django 5.0.4 on 2024-06-17 17:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_user_is_assigned_to_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='AscKamavota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, dim=3, null=True, srid=4326)),
                ('oid_field', models.BigIntegerField(blank=True, db_column='oid_', null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('folderpath', models.CharField(blank=True, max_length=254, null=True)),
                ('symbolid', models.BigIntegerField(blank=True, null=True)),
                ('altmode', models.BigIntegerField(blank=True, null=True)),
                ('base', models.FloatField(blank=True, null=True)),
                ('clamped', models.BigIntegerField(blank=True, null=True)),
                ('extruded', models.BigIntegerField(blank=True, null=True)),
                ('snippet', models.CharField(blank=True, max_length=254, null=True)),
                ('popupinfo', models.CharField(blank=True, max_length=254, null=True)),
                ('shape_leng', models.FloatField(blank=True, null=True)),
                ('shape_area', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ASC- Kamavota',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='direccao_regional',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='asc',
            name='direccao_regional',
        ),
        migrations.AlterField(
            model_name='asc',
            name='nome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.asckamavota'),
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
        migrations.DeleteModel(
            name='Direccao_Regional',
        ),
    ]
