# Generated by Django 5.0.3 on 2024-04-05 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_usuario_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asc',
            old_name='sigla_ASC',
            new_name='codigo_ASC',
        ),
    ]
