# Generated by Django 5.0.3 on 2024-04-05 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_rename_sigla_asc_asc_codigo_asc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(default=1, auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_provincia', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='asc',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.provincia'),
        ),
    ]
