# Generated by Django 5.0.3 on 2024-04-05 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_provincia_asc_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asc',
            name='provincia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.provincia'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nome_provincia',
            field=models.CharField(max_length=50),
        ),
    ]
