# Generated by Django 5.0.3 on 2024-04-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_asc_provincia_alter_provincia_nome_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
