# Generated by Django 5.0.3 on 2024-04-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_alter_provincia_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccao_Regional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_direccao', models.CharField(max_length=10)),
            ],
        ),
    ]
