# Generated by Django 5.0.3 on 2024-04-05 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_direccao_regional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asc',
            name='direccao_regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.direccao_regional'),
        ),
    ]
