# Generated by Django 5.0.3 on 2024-04-05 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_asc_direccao_regional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asc',
            name='provincia',
        ),
        migrations.AddField(
            model_name='direccao_regional',
            name='provincia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.provincia'),
        ),
    ]
