# Generated by Django 5.0.3 on 2024-04-05 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_remove_asc_provincia_direccao_regional_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccao_regional',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.provincia'),
        ),
    ]
