# Generated by Django 5.0.3 on 2024-04-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_alter_direccao_regional_provincia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccao_regional',
            name='nome_direccao',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
