# Generated by Django 5.0.4 on 2024-05-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='task',
            name='acess_denied',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='task',
            name='meter_box',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='task',
            name='premisses_Locked',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
