# Generated by Django 5.0.4 on 2024-05-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_alter_task_acess_denied_alter_task_meter_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='acess_denied',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='meter_box',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='premisses_Locked',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
