# Generated by Django 5.0.4 on 2024-05-09 10:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('asc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.asc')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_teams', to=settings.AUTH_USER_MODEL)),
                ('membros', models.ManyToManyField(limit_choices_to={'user_type__in': ['tecnico_campo']}, related_name='teams_members', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ManyToManyField(limit_choices_to={'user_type__in': ['supervisor_campo']}, related_name='teams_supervisor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
