# Generated by Django 5.0.4 on 2024-04-26 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0002_provincia_alter_direccao_regional_nome_direccao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reject', 'Rejeitado')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('asc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.asc')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_teams', to=settings.AUTH_USER_MODEL)),
                ('membros', models.ManyToManyField(limit_choices_to={'user_type__in': ['tecnico_campo']}, related_name='teams_members', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Team.state')),
                ('supervisor', models.ManyToManyField(limit_choices_to={'user_type__in': ['supervisor_campo']}, related_name='teams_supervisor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
