# Generated by Django 5.0.4 on 2024-04-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
