# Generated by Django 5.0.4 on 2024-05-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0004_team_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
