# Generated by Django 5.0.4 on 2024-06-13 00:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0005_alter_team_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='membros_1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='membros',
        ),
        migrations.AddField(
            model_name='team',
            name='membros',
            field=models.ManyToManyField(limit_choices_to={'user_type__in': ['tecnico_campo']}, related_name='teams_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
