# Generated by Django 5.0.4 on 2024-06-14 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0006_remove_team_membros_1_remove_team_membros_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
    ]
