# Generated by Django 5.0.4 on 2024-05-09 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('submetido', 'Submetido'), ('reijeitado', 'Reijeitado')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Project_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('project_new', 'Projecto - Novo Levantamento'), ('project_feeder', 'Projecto - Novo PT Feeder '), ('project_correcao', 'Projecto - Levantamento Correcao'), ('project_pl', 'Projecto - Premisses Locked')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PT_NUMBER', models.CharField(max_length=20)),
                ('asc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.asc')),
            ],
        ),
        migrations.CreateModel(
            name='Projecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.pt')),
            ],
        ),
        migrations.CreateModel(
            name='LV_Feeder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('PT', models.ManyToManyField(default=1, to='Project.pt')),
            ],
        ),
    ]
