# Generated by Django 5.0.4 on 2024-05-09 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
        ('Team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecto',
            name='nome',
        ),
        migrations.AddField(
            model_name='projecto',
            name='LV',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Project.lv_feeder'),
        ),
        migrations.AddField(
            model_name='projecto',
            name='equipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Team.team'),
        ),
        migrations.AddField(
            model_name='projecto',
            name='perfil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Project.estado'),
        ),
        migrations.AddField(
            model_name='projecto',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Project.project_type'),
        ),
        migrations.AlterField(
            model_name='lv_feeder',
            name='PT',
            field=models.ManyToManyField(to='Project.pt'),
        ),
    ]
