# Generated by Django 5.0.4 on 2024-05-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_remove_projecto_nome_projecto_lv_projecto_equipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('submetido', 'Submetido'), ('reijeitado', 'Reijeitado')], max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='project_type',
            name='type',
            field=models.CharField(choices=[('project_new', 'Projecto - Novo Levantamento'), ('project_feeder', 'Projecto - Novo PT Feeder '), ('project_correcao', 'Projecto - Levantamento Correcao'), ('project_pl', 'Projecto - Premisses Locked')], max_length=30, unique=True),
        ),
    ]
