# Generated by Django 5.0.4 on 2024-05-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_alter_estado_status_alter_project_type_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_type',
            name='type',
            field=models.CharField(choices=[('Novo Levantamento', 'Projecto - Novo Levantamento'), ('Novo PT Feeder ', 'Projecto - Novo PT Feeder '), ('Levantamento Correction', 'Projecto - Levantamento Correction'), ('Premisses Locked', 'Projecto - Premisses Locked')], max_length=30, unique=True),
        ),
    ]
