# Generated by Django 5.0.4 on 2024-06-14 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_remove_projecto_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
