# Generated by Django 5.0.4 on 2024-06-17 18:17

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0010_alter_projecto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostoDeTransformao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('id_0', models.IntegerField(blank=True, db_column='ID', null=True)),
                ('pt_number', models.CharField(blank=True, db_column='PT NUMBER', null=True)),
                ('latittude', models.FloatField(blank=True, db_column='Latittude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='Longitude', null=True)),
            ],
            options={
                'db_table': 'Posto de Transformação ',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='lv_feeder',
            name='PT',
        ),
        migrations.AddField(
            model_name='lv_feeder',
            name='PT',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saidas', to='Project.postodetransformao'),
        ),
    ]
